baseURL = ""
theme = 'hugo-bearblog'
title = "IWantTo.Blog"
author = "Steward Righteous"
copyright = "Copyright © 2025, Steward Righteous."
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "I want to is a personal blog website that talks about various philosophical concepts of life "
  favicon = "images/favicon_1.png"
  images = ["images/share.png"]
  title = "I want to"
  hideMadeWithLine = true
  dateFormat = "2006/Jan/02 ->"
